apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-frontend
  namespace: lms
  labels:
    app: lms-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lms-frontend
  template:
    metadata:
      labels:
        app: lms-frontend
    spec:
      containers:
        - name: lms-frontend
          image: vishnumohan9447/lms-frontend:23
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
