apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "25.8.0"
    chart: kube-prometheus-stack
    helm:
      releaseName: monitoring
      values:
        grafana:
          persistence:
            enabled: false
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
        prometheus:
          prometheusSpec:
            resources:
              requests:
                cpu: 200m
                memory: 400Mi
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: ""
                  resources:
                    requests:
                      storage: 2Gi
        alertmanager:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
