grafana:
  enabled: true

  adminPassword: admin123

  persistence:
    enabled: false

prometheus:
  prometheusSpec:
    retention: 7d

    storageSpec: {}

    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

alertmanager:
  enabled: true

  alertmanagerSpec:
    storage: {}

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
