loki:
  useTestSchema: true

  auth_enabled: false

  persistence:
    enabled: false

  resources:
    requests:
      cpu: 100m
      memory: 300Mi
    limits:
      cpu: 200m
      memory: 600Mi

deploymentMode: SingleBinary

singleBinary:
  replicas: 1

backend:
  replicas: 0

read:
  replicas: 0

write:
  replicas: 0
